[tool.poetry]
name = "nullingexplorer"
version = "0.1.0"
description = ""
authors = ["Mary Tim <reitingma1996@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
